apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  username: <base64_encoded_username>
  password: <base64_encoded_password>
  database: <base64_encoded_database_name>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: my-app-image:latest
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: database
# Kubernetes Secret named db-credentials, which contains secure credentials such as username, password, and database name as base64-encoded values.
# I'm using this Secret to store and expose the credentials.
#The Deployment YAML file references the secret and exposes the credentials as environment variables (DB_USERNAME, DB_PASSWORD, and DB_DATABASE) within the container.
# These environment variables could then be accessed by the application for various purposes, such as logging or debugging
