apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: kustomize-

resources:
#- nginx-configmap.yaml
#- nginx-deployment.yaml 
#- nginx-svc.yaml
#- fake_credentials.yaml

commonAnnotations:
  channel: justopensource
