apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-test-site
  namespace: argocd
spec:
  project: default # Set the project name here

  source:
    repoURL: https://github.com/debolek/Debolek_Devops_Task.git
    targetRevision: HEAD
    path: Prod
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    
