apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-test-site
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'default'
  source:
    repoURL: https://github.com/debolek/Debolek_Devops_Task.git  # Replace with your GitHub repository URL
    path: /Users/debolek/Desktop/Debolek_Devops/Debolek_Devops_Task/argocd-app-config/prod
    targetRevision: HEAD
  project: 'default'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
