apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Welcome to Nginx Test Site</title>
    </head>
    <body>
      <h1>Hello from Nginx Deployment</h1>
    </body>
    </html>
